### ISSUE TITLE
Uncaught TypeError: _this.browser.createPage is not a function

### ISSUE THREAD

**Issue by mradzinski** [gstack/atom-browser-webview#18]
Tried using it for the first time...

**Atom Version**: 1.2.4
**System**: Windows 10
**Thrown From**: [atom-webbrowser](https://github.com/gstack/atom-browser-webview) package, v2.1.1
### Stack Trace

Uncaught TypeError: _this.browser.createPage is not a function

```
At /C:/Users/Admin/.atom/packages/atom-webbrowser/lib/omnibox-view.coffee:51

TypeError: _this.browser.createPage is not a function
    at HTMLInputElement.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-webbrowser/lib/omnibox-view.coffee:28:38)
    at HTMLInputElement.jQuery.event.dispatch (C:\Users\Admin\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (C:\Users\Admin\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```
### Commands

```
     -2:43.5.0 turbo-javascript:end-line-comma (atom-text-editor.editor.is-focused)
     -2:42.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:40.1.0 settings-view:open (atom-text-editor.editor)
     -1:57 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:55.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:23 web-browser:toggle (div.package-detail.panels-item)
     -0:02.3.0 terminal-plus:insert-selected-text (input.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "autosave",
      "file-icons"
    ],
    "audioBeep": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "tool-bar",
      "highlight-selected",
      "ask-stack"
    ]
  },
  "atom-webbrowser": {}
}
```
### Installed Packages

``` coffee
# User
atom-clock, v0.0.5
atom-grails, v0.1.0
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
atom-webbrowser, v2.1.1
clipboard-plus, v0.5.1
color-picker, v2.0.14
data-atom, v0.17.1
docblockr, v0.7.3
fonts, v1.0.0
git-log, v0.4.1
highlight-selected, v0.11.1
imdone-atom, v1.3.3
jquery-snippets, v11.0.0
jshint, v1.8.3
language-diff, v0.4.0
language-groovy, v0.4.0
minimap, v4.16.2
open-recent, v4.0.1
pigments, v0.19.1
pretty-json, v0.4.1
project-manager, v2.6.5
project-view, v0.3.0
saveallthetime, v0.2.1
terminal-plus, v0.14.5
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tree-view-git-status, v0.2.2
turbo-javascript, v1.2.0

# Dev
No dev packages
```

**Comment by lynchpin4** [comment]
This should be fixed, mind checking for me to see if I can close the issue?

Windows appears to be working now.
