### ISSUE TITLE
Uncaught TypeError: _ref1.getWebview is not a function

### ISSUE THREAD

**Issue by komasoftware** [gstack/atom-browser-webview#19]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Ubuntu 15.10
**Thrown From**: [atom-webbrowser](https://github.com/gstack/atom-browser-webview) package, v2.1.4
### Stack Trace

Uncaught TypeError: _ref1.getWebview is not a function

```
At /home/koen/.atom/packages/atom-webbrowser/lib/web-browser.coffee:56

TypeError: _ref1.getWebview is not a function
    at atom-workspace.atom.commands.add.web-browser:devtools (/home/koen/.atom/packages/atom-webbrowser/lib/web-browser.coffee:56:52)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1010:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -4:19.8.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -4:10 terminal-plus:new (atom-text-editor.editor.is-focused)
     -3:30.8.0 golang:goinfo (atom-text-editor.editor.is-focused)
     -2:46.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:46 web-browser:newtab (div.package-detail.panels-item)
  3x -0:38.5.0 web-browser:devtools (webview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "environment"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "atom-webbrowser": {}
}
```
### Installed Packages

``` coffee
# User
atom-webbrowser, v2.1.4
autocomplete-go, v0.1.1
autocomplete-plus, v2.25.0
go-config, v0.3.1
go-plus, v3.5.2
language-gradle, v0.0.3
linter, v1.11.3
linter-js-yaml, v1.2.5
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by nikandlv** [comment]
+1
