### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jpietrangelo** [gstack/atom-browser-webview#3]
[Enter steps to reproduce below:]
1. ... Just download and installed the plugin. Tried opening up a local site. It let me open the site, but the error pops up everytime I click the refresh icon.

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-browser-webview](https://github.com/gstack/atom-browser-webview) package, v0.4.7
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jmp/.atom/packages/atom-browser-webview/lib/page-view.coffee:79

TypeError: undefined is not a function
  at PageView.module.exports.PageView.reload (/Users/jmp/.atom/packages/atom-browser-webview/lib/page-view.coffee:79:16)
  at Page.module.exports.Page.reload (/Users/jmp/.atom/packages/atom-browser-webview/lib/page.coffee:79:16)
  at WebBrowser.refresh (/Users/jmp/.atom/packages/atom-browser-webview/lib/web-browser.coffee:171:25)
  at HTMLDivElement.<anonymous> (/Users/jmp/.atom/packages/atom-browser-webview/lib/toolbar-view.coffee:50:43)
  at HTMLDivElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -1:46.9 open-in-browser:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:59.3 web-browser:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.9 fuzzy-finder:toggle-buffer-finder (input.native-key-bindings)
     -0:17.6 core:move-down (atom-text-editor.editor.mini)
     -0:10.7 fuzzy-finder:toggle-buffer-finder (input.native-key-bindings)
     -0:09.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:09.4 core:cancel (atom-text-editor.editor.mini)
     -0:07.6 fuzzy-finder:toggle-buffer-finder (input.native-key-bindings)
     -0:02.6 core:paste (input.native-key-bindings)
  2x -0:00.0 did-finish-load (webview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "web-browser"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/jmp/Documents/GitHub\\ Projects"
  },
  "atom-browser-webview": {}
}
```
### Installed Packages

``` coffee
# User
atom-browser-webview, v0.4.7
color-picker, v1.3.0
emmet, v2.3.2
file-icons, v1.4.6
linter, v0.10.0
minimap, v3.5.6
open-in-browser, v0.3.0
project-manager, v1.14.1
script, v2.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lacostenycoder** [comment]
I'm having same issue... any ideas?

**Comment by aalonzolu** [comment]
Same here.

**Comment by ghost** [comment]
[Enter steps to reproduce below:]
1. open file
2. open atom browser
3. restart atom
4. close file
5. PROFIT!!! (or more like: atom browser crach)

**Atom Version**: 0.184.0
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [atom-browser-webview](https://github.com/gstack/atom-browser-webview) package, v0.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\web-browser.coffee:197

TypeError: undefined is not a function
  at WebBrowser.refresh (C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\web-browser.coffee:197:48)
  at HTMLDivElement.<anonymous> (C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\toolbar-view.coffee:49:43)
  at HTMLDivElement.handler (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:34.2 did-finish-load (webview.native-key-bindings)
     -0:26.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:23.9 core:backspace (atom-text-editor.editor.mini)
  2x -0:21.4 core:move-down (atom-text-editor.editor.mini)
     -0:13.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:13.1 core:cancel (atom-text-editor.editor.mini)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "atom-browser-webview": {}
}
```

### Installed Packages

``` coffee
# User
atom-browser-webview, v0.6.0
language-gradle, v0.0.3
language-groovy, v0.3.0
linter, v0.12.0
linter-javac, v0.1.3
seti-syntax, v0.3.3
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
[Enter steps to reproduce below:]
1. open browser
2. click on refresh

**Atom Version**: 0.184.0
**System**: Microsoft Windows 8 Enterprise
**Thrown From**: [atom-browser-webview](https://github.com/gstack/atom-browser-webview) package, v0.6.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\web-browser.coffee:197

TypeError: undefined is not a function
  at WebBrowser.refresh (C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\web-browser.coffee:197:48)
  at HTMLDivElement.<anonymous> (C:\Users\theprophet31337\.atom\packages\atom-browser-webview\lib\toolbar-view.coffee:49:43)
  at HTMLDivElement.handler (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDivElement.elemData.handle (C:\Users\theprophet31337\AppData\Local\atom\app-0.184.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -4:40.1 did-finish-load (webview.native-key-bindings)
     -4:32.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:29.8 core:backspace (atom-text-editor.editor.mini)
  2x -4:27.3 core:move-down (atom-text-editor.editor.mini)
     -4:19.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:19.0 core:cancel (atom-text-editor.editor.mini)
     -0:23.3 command-palette:toggle (atom-text-editor.editor)
  3x -0:20.1 core:move-down (atom-text-editor.editor.mini)
     -0:17.1 core:confirm (atom-text-editor.editor.mini)
     -0:17.1 web-browser:toggle (atom-text-editor.editor)
     -0:09.4 did-finish-load (webview.native-key-bindings)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "atom-browser-webview": {}
}
```

### Installed Packages

``` coffee
# User
atom-browser-webview, v0.6.0
language-gradle, v0.0.3
language-groovy, v0.3.0
linter, v0.12.0
linter-javac, v0.1.3
seti-syntax, v0.3.3
text-manipulation, v0.4.0

# Dev
No dev packages
```
