### ISSUE TITLE
Uncaught TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by mabdurrahman** [gstack/atom-browser-webview#37]
Steps to reproduce:

1. Open any webpage with links which are of blank type
2. Click any of blank links
3. Watch out the newly opened tab, it misses the address bar view + its height is trimmed + raising the exception below

OR

1. Open any web pages with links
2. Try to open any link in new tab
3. Watch out the newly opened tab, it misses the address bar view + its height is trimmed + raising the exception below

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [atom-webbrowser](https://github.com/gstack/atom-browser-webview) package, v2.1.4

### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At url.js:87

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at Page.module.exports.Page.update (/Users/mabdurrahman/.atom/packages/atom-webbrowser/lib/page.coffee:54:29)
    at Page.module.exports.Page.locationChanged (/Users/mabdurrahman/.atom/packages/atom-webbrowser/lib/page.coffee:39:6)
    at webview.<anonymous> (/Users/mabdurrahman/.atom/packages/atom-webbrowser/lib/page-view.coffee:32:18)
    at webview.dispatch (/Users/mabdurrahman/.atom/packages/atom-webbrowser/node_modules/jquery/dist/jquery.js:4435:9)
    at webview.elemData.handle (/Users/mabdurrahman/.atom/packages/atom-webbrowser/node_modules/jquery/dist/jquery.js:4121:28)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -0:50.3.0 application:new-file (div.panels)
     -0:44.1.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
atom-typescript, v10.1.13 (inactive)
atom-webbrowser, v2.1.4 (active)
browser-plus, v0.0.87 (active)
browser-plus-open-new-window, v0.0.1 (active)
browser-plus-zoom, v0.0.2 (active)
custom-title, v1.0.1 (active)
open-recent, v5.0.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dov-yih** [comment]
[Enter steps to reproduce:]

1. once the URL has changed, it will report this error.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [atom-webbrowser](https://github.com/gstack/atom-browser-webview) package 2.1.4


### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At url.js:87

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at Page.module.exports.Page.update (/packages/atom-webbrowser/lib/page.coffee:54:29)
    at Page.module.exports.Page.locationChanged (/packages/atom-webbrowser/lib/page.coffee:39:6)
    at /packages/atom-webbrowser/lib/page-view.coffee:32:18)
    at webview.dispatch (/packages/git-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at webview.elemData.handle (/packages/git-plus/node_modules/jquery/dist/jquery.js:4121:28)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -8:48.3.0 core:save (input.hidden-input)
     -3:41.6.0 tree-view:add-file (span.name.icon.icon-repo)
     -3:37.1.0 core:confirm (input.hidden-input)
     -3:34.7.0 intentions:highlight (input.hidden-input)
     -3:34.2.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -3:32.8.0 intentions:highlight (input.hidden-input)
     -3:32.6.0 core:paste (input.hidden-input)
     -3:31.3.0 intentions:highlight (input.hidden-input)
     -3:30.9.0 core:save (input.hidden-input)
     -3:25.8.0 intentions:highlight (input.hidden-input)
     -3:24.6.0 application:new-window (input.hidden-input)
  3x -3:12.6.0 intentions:highlight (input.hidden-input)
     -3:05.7.0 emmet:merge-lines (input.hidden-input)
     -2:46.9.0 intentions:highlight (input.hidden-input)
     -2:46.7.0 command-palette:toggle (input.hidden-input)
     -2:40 markdown-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
angularjs 0.4.0 
angularjs-styleguide-snippets 0.9.1 
angularjs-styleguide-webpack-snippets 1.1.0 
atom-angular-material-snippets 1.3.0 
atom-angular-snippets 1.0.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.29.24 
atom-clock 0.1.12 
atom-material-syntax 0.4.6 
atom-material-ui 1.3.9 
atom-text-transformer 0.7.0 
atom-transpose 0.3.4 
atom-webbrowser 2.1.4 
atom-zh-dictionary 0.4.4 
autoclose-html 0.23.0 
autocomplete-angular-material 0.4.0 
autocomplete-java 1.2.5 
busy-signal 1.4.3 
color-picker 2.2.5 
dash-ui 0.4.0 
emmet 2.4.3 
git-log 0.4.1 
git-plus 7.3.3 
git-plus-plus 1.1.0 
git-time-machine 1.5.9 
intentions 1.1.2 
java-generator 2.2.3 
java-importer 1.4.1 
jshint 1.8.6 
language-markdown 0.20.0 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
loved-syntax 1.0.1 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.6.4 
minimap 4.26.8 
node-debugger 1.10.1 
open-in-browser 0.4.7 
php-cs-fixer 4.1.0 
pristine-ui 1.0.15 
script 3.14.1 
seti-syntax 1.1.2 
seti-ui 1.4.0 
Tia-ui 1.0.3 
trans-en-zh 0.2.5 
```
