### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by aalonzolu** [gstack/atom-browser-webview#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.18.4-1-ARCH
**Thrown From**: [atom-browser-webview](https://github.com/gstack/atom-browser-webview) package, v0.6.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At /usr/share/atom/resources/atom/renderer/lib/web-view.js:654

TypeError: Cannot read property 'getTitle' of undefined
  at webview.getTitle (/usr/share/atom/resources/atom/renderer/lib/web-view.js:654:77)
  at PageView.module.exports.PageView.getTitle (/home/andy/.atom/packages/atom-browser-webview/lib/page-view.coffee:42:22)
  at Page.module.exports.Page.getTitle (/home/andy/.atom/packages/atom-browser-webview/lib/page.coffee:20:24)
  at Workspace.module.exports.Workspace.updateWindowTitle (/usr/share/atom/resources/app/src/workspace.js:237:86)
  at Workspace.updateWindowTitle (/usr/share/atom/resources/app/src/workspace.js:3:61)
  at /usr/share/atom/resources/app/src/workspace.js:196:17
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:314:21)
  at WebBrowser.createPage (/home/andy/.atom/packages/atom-browser-webview/lib/web-browser.coffee:156:31)
  at WebBrowser.setLocation (/home/andy/.atom/packages/atom-browser-webview/lib/web-browser.coffee:166:11)
  at HTMLInputElement.<anonymous> (/home/andy/.atom/packages/atom-browser-webview/lib/omnibox-view.coffee:30:37)
  at HTMLInputElement.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLInputElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLInputElement.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -2:08.6 core:confirm (input.hidden-input)
     -2:08.4 web-view:go-to-page (input.hidden-input)
     -2:06.8 core:paste (input.hidden-input)
     -2:05.4 core:undo (input.hidden-input)
     -2:04.4 command-palette:toggle (input.hidden-input)
     -2:00.7 web-view:go-to-page (input.hidden-input)
     -1:57.9 core:paste (input.hidden-input)
     -1:56.4 core:confirm (input.hidden-input)
     -1:27.2 command-palette:toggle (input.hidden-input)
  2x -1:23.0 core:move-down (input.hidden-input)
     -1:21.9 core:confirm (input.hidden-input)
     -1:21.8 settings-view:install-packages (input.hidden-input)
     -1:17.5 core:confirm (input.hidden-input)
     -0:03.3 command-palette:toggle (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
     -0:00.0 web-browser:toggle (input.hidden-input)
```
### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-browser-webview, v0.6.0
autocomplete-plus, v2.1.3
monokai, v0.12.0
remote-sync, v2.4.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by tommitch** [comment]
I'm getting this issue on OS X 10.10.2 as well. I've not found a way to consistently reproduce the issue but it seems to be something to do with using it with multiple panes. 

I have found you can get around the error for now by doing the following;
1. Switch to a different tab
2. Toggle the browser toolbar `ctrl+alt+b` twice so that it's disappears then shows again
3. Switch back to the browser tab
